const telegram=window.Telegram?.WebApp;if(telegram){telegram.ready();telegram.expand();}
const cashflowData={date:"14.07.2026",companies:[
{code:"ЗЗД",name:"ЗЕРНОЗБУД",accent:"#15803d",opening:7561913.56,income:482300,payments:315800,closing:7728413.56,details:{income:[{counterparty:"ТОВ «Агро Партнер»",purpose:"Оплата за поставлене зерно",amount:300000},{counterparty:"ТОВ «Трейд Сервіс»",purpose:"Погашення дебіторської заборгованості",amount:182300}],payments:[{counterparty:"ТОВ «Добрива Плюс»",purpose:"Оплата за мінеральні добрива",amount:185800},{counterparty:"Податки",purpose:"ПДВ та обов'язкові платежі",amount:130000}]}},
{code:"МЛ",name:"МАТІОС ЛОГІСТІК",accent:"#1d4ed8",opening:2258981.97,income:140000,payments:96500,closing:2302481.97,details:{income:[{counterparty:"ТОВ «Карго Груп»",purpose:"Оплата логістичних послуг",amount:140000}],payments:[{counterparty:"Паливна компанія",purpose:"Дизельне пальне",amount:61500},{counterparty:"СТО",purpose:"Технічне обслуговування транспорту",amount:35000}]}},
{code:"КВ",name:"КВ АГРО ГРУП",accent:"#c2410c",opening:3045764.15,income:275000,payments:198750,closing:3122014.15,details:{income:[{counterparty:"ТОВ «Зерно Інвест»",purpose:"Оплата за товар",amount:275000}],payments:[{counterparty:"ТОВ «Насіння Україна»",purpose:"Оплата за посівний матеріал",amount:128750},{counterparty:"Оренда",purpose:"Орендна плата за склад",amount:70000}]}},
{code:"БС",name:"БАЗА СЕРВІС",accent:"#6d28d9",opening:75595.38,income:42000,payments:18500,closing:99095.38,details:{income:[{counterparty:"ТОВ «Сервіс Лайн»",purpose:"Оплата за послуги",amount:42000}],payments:[{counterparty:"Комунальні послуги",purpose:"Електроенергія та водопостачання",amount:18500}]}}
]};
const $=id=>document.getElementById(id);const fmt=v=>new Intl.NumberFormat("uk-UA",{minimumFractionDigits:2,maximumFractionDigits:2}).format(v)+" ₴";
function render(){$("reportDate").textContent=cashflowData.date;$("totalClosing").textContent=fmt(cashflowData.companies.reduce((s,c)=>s+c.closing,0));$("companiesGrid").innerHTML=cashflowData.companies.map((c,i)=>`<article class="company-card"><header class="company-header"><div class="company-identity"><div class="company-mark" style="background:${c.accent}">${c.code}</div><div><strong class="company-name">${c.code}</strong><span class="company-full-name">${c.name}</span></div></div><div class="closing-value"><span>На кінець дня</span><strong>${fmt(c.closing)}</strong></div></header><div class="flows"><div class="flow-row"><div class="flow-label"><span class="flow-dot" style="background:#94a3b8"></span><span>На початок дня</span></div><strong class="flow-value">${fmt(c.opening)}</strong></div><button class="flow-row clickable income" data-i="${i}" data-t="income"><div class="flow-label"><span class="flow-dot" style="background:#22c55e"></span><span>Надходження</span></div><strong class="flow-value">+ ${fmt(c.income)} <span class="flow-chevron">›</span></strong></button><button class="flow-row clickable payment" data-i="${i}" data-t="payments"><div class="flow-label"><span class="flow-dot" style="background:#ef4444"></span><span>Платежі</span></div><strong class="flow-value">− ${fmt(c.payments)} <span class="flow-chevron">›</span></strong></button></div></article>`).join("");document.querySelectorAll(".clickable").forEach(b=>b.onclick=()=>openDetails(+b.dataset.i,b.dataset.t));}
function openDetails(i,t){const c=cashflowData.companies[i],ops=c.details[t]||[];$("modalCompany").textContent=`${c.code} · ${c.name}`;$("modalTitle").textContent=t==="income"?"Надходження":"Платежі";$("modalTotal").textContent=fmt(ops.reduce((s,x)=>s+x.amount,0));$("operationsList").innerHTML=ops.map(x=>`<article class="operation-card"><div class="operation-top"><div class="operation-name">${x.counterparty}</div><div class="operation-amount">${fmt(x.amount)}</div></div><p class="operation-purpose">${x.purpose}</p></article>`).join("");$("detailsModal").classList.remove("hidden");telegram?.HapticFeedback?.impactOccurred("light");}
function close(){$("detailsModal").classList.add("hidden")}
$("closeModal").onclick=close;$("detailsModal").onclick=e=>{if(e.target===$("detailsModal"))close()};$("refreshButton").onclick=()=>{$("syncNote").textContent="Дані оновлено. Поки використовується демо-режим."};$("previousDay").onclick=$("nextDay").onclick=()=>alert("Вибір дати підключимо наступним кроком.");render();
